name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # umožní publikovať do GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tag
      id: vars
      run: echo "tag=ghcr.io/${{ github.repository }}:$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.vars.outputs.tag }}

    - name: Push Docker image to GHCR
      run: docker push ${{ steps.vars.outputs.tag }}
